#include "data.h"
#include "planet.h"

/* Everything in this file is to be moved into configuration
 * files in the future. */

/* Planetary classification is inspired by Star Trek canon, see
 * https://en.wikipedia.org/wiki/Class_M_planet
 * http://www.sttff.net/planetaryclass.html */

const char planet_life_desc[LIFE_NUM][PLANET_LIFE_DESC_LEN] = {
	"Toxic to life",
	"Barren, no life",
	"Dead planet",
	"Single-cellular life",
	"Bacterial life",
	"Simple lifeforms",
	"Resistant plantlife",
	"Complex plantlife",
	"Animal life",
	"Intelligent humanoid life"
};


struct planet_type planet_types[PLANET_TYPE_N] = {
	{
		.c       = 'A',
		.name    = "Volcanic world",
		.desc    = "Long description ... ",
		.surface = "Partially molten",
		.atmo    = "Carbon dioxide and hydrogen",
		.zones   = {1, 1, 0},
		.mindia  = 10,
		.maxdia  = 100,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
	{
		.c       = 'B',
		.name    = "Molten world",
		.desc    = "Long description ... ",
		.atmo    = "Thin, primarily helium and sodium",
		.surface = "Partially molten",
		.zones   = {1, 0, 0},
		.mindia  = 10,
		.maxdia  = 100,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
	{
		.c       = 'C',
		.name    = "Barren, dead world",
		.desc    = "Long description ... ",
		.atmo    = "Extremely thin to none",
		.surface = "Barren, dead",
		.zones   = {1, 1, 1},
		.mindia  = 10,
		.maxdia  = 100,
		.minlife = BARREN,
		.maxlife = BARREN,
	},
	{
		.c       = 'D',
		.name    = "Dwarven planetoid",
		.desc    = "Long description ... ",
		.atmo    = "Extremely thin to none",
		.surface = "Barren, cratered",
		.zones   = {1, 1, 1},
		.mindia  = 10,
		.maxdia  = 40,
		.minlife = DEAD,
		.maxlife = DEAD,
	},
	{
		.c       = 'E',
		.name    = "Molten prototerrestrial",
		.desc    = "Long description ... ",
		.atmo    = "Hydrogen compounds and helium",
		.surface = "Partially molten",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = DEAD,
		.maxlife = SINGLECELL,
	},
	{
		.c       = 'F',
		.name    = "Volcanic prototerrestrial",
		.desc    = "Long description ... ",
		.atmo    = "Primarily carbon dioxide, ammonia and methane",
		.surface = "Barren, volcanic",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = SINGLECELL,
		.maxlife = BACTERIA,
	},
	{
		.c       = 'G',
		.name    = "Barren prototerrestrial",
		.desc    = "Long description ... ",
		.atmo    = "Primarily carbon dioxide, oxygen and nitrogen",
		.surface = "Rocky and barren",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = BACTERIA,
		.maxlife = SIMPLE,
	},
	{
		.c       = 'H',
		.name    = "Harsh desert world",
		.desc    = "Long description ... ",
		.atmo    = "Primarily oxygen, nitrogen and argon",
		.surface = "Arid",
		.zones   = {0, 1, 0},
		.mindia  = 80,
		.maxdia  = 150,
		.minlife = BACTERIA,
		.maxlife = RESISTANT
	},
	{
		.c       = 'I',
		.name    = "Gas ice giant",
		.desc    = "Long description ... ",
		.atmo    = "Primarily hydrogen and helium",
		.surface = "Methane and ammonia ice",
		.zones   = {0, 0, 1},
		.mindia  = 300,
		.maxdia  = 1000,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
	{
		.c       = 'J',
		.name    = "Gas giant",
		.desc    = "Long description ... ",
		.atmo    = "Primarily hydrogen and helium",
		.surface = "Liquid metallic hydrogen",
		.zones   = {0, 0, 1},
		.mindia  = 500,
		.maxdia  = 5000,
		.minlife = TOXIC,
		.maxlife = TOXIC
	},
	{
		.c       = 'K',
		.name    = "Barren world",
		.desc    = "Long description ... ",
		.atmo    = "Thin carbon dioxide",
		.surface = "Barren, arid",
		.zones   = {0, 1, 0},
		.mindia  = 50,
		.maxdia  = 100,
		.minlife = DEAD,
		.maxlife = SIMPLE
	},
	{
		.c       = 'L',
		.name    = "Primitive atmosphere",
		.desc    = "Long description ... ",
		.atmo    = "Primarily argon and oxygen",
		.surface = "Rocky, forested", 
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = RESISTANT,
		.maxlife = COMPLEX
	},
	{
		.c       = 'M',
		.name    = "Terrestrial world",
		.desc    = "Long description ... ",
		.atmo    = "Primarily nitrogen and oxygen",
		.surface = "Temperate climate",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = COMPLEX,
		.maxlife = INTELLIGENT
	},
	{
		.c       = 'N',
		.name    = "Sulfuric, corrosive world",
		.desc    = "Long description ... ",
		.atmo    = "Carbon dioxide and sulfides",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = TOXIC,
		.maxlife = BACTERIA
	},
	{
		.c       = 'O',
		.name    = "Water world",
		.desc    = "Long description ... ",
		.atmo    = "Nitrogen and oxygen",
		.surface = "Oceanic",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = COMPLEX,
		.maxlife = INTELLIGENT
	},
	{
		.c       = 'P',
		.name    = "Frozen water world",
		.desc    = "Long description ... ",
		.atmo    = "Nitrogen and oxygen",
		.surface = "Water ice",
		.zones   = {0, 1, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = RESISTANT,
		.maxlife = ANIMAL
	},
	{
		.c       = 'S',
		.name    = "Gas supergiant",
		.desc    = "Long description ... ",
		.atmo    = "Hydrogen and helium",
		.surface = "Liquid metallic hydrogen",
		.zones   = {0, 0, 1},
		.mindia  = 5000,
		.maxdia  = 1000000,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
	{
		.c       = 'T',
		.name    = "Gas ultragiant",
		.desc    = "Long description ... ",
		.atmo    = "Hydrogen and helium",
		.surface = "Liquid hydrogen",
		.zones   = {0, 0, 1},
		.mindia  = 500000,
		.maxdia  = 2000000,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
	{
		.c       = 'Y',
		.name    = "Demon world",
		.desc    = "Demon worlds are extremely hostile to life, often combining high radiation, hot temperatures and toxic atmospheres.",
		.atmo    = "Turbulent, toxic",
		.surface = "Barren",
		.zones   = {1, 0, 0},
		.mindia  = 100,
		.maxdia  = 150,
		.minlife = TOXIC,
		.maxlife = TOXIC,
	},
};
